import { jsPDF } from "jspdf";
import { addChineseFont } from "@/lib/chinese-font";

// Language translations for PDF content
export const pdfTranslations = {
  en: {
    title: "TCM Diagnosis Report",
    subtitle: "Traditional Chinese Medicine Analysis",
    generated: "Generated",
    mainDiagnosis: "MAIN DIAGNOSIS",
    constitution: "Constitution",
    detailedAnalysis: "DETAILED ANALYSIS",
    dietaryRecommendations: "DIETARY RECOMMENDATIONS",
    recommendedFoods: "Recommended Foods:",
    foodsToAvoid: "Foods to Avoid:",
    lifestyleRecommendations: "LIFESTYLE RECOMMENDATIONS",
    exercise: "EXERCISE SUGGESTIONS",
    acupoints: "ACUPOINTS",
    footer1: "This report is generated by Sihat TCM AI Assistant for informational purposes only.",
    footer2: "Please consult a licensed TCM practitioner for professional medical advice.",
    fileName: "TCM_Diagnosis",
  },
  zh: {
    title: "中医诊断报告",
    subtitle: "传统中医药分析",
    generated: "生成日期",
    mainDiagnosis: "主要诊断",
    constitution: "体质",
    detailedAnalysis: "详细分析",
    dietaryRecommendations: "饮食建议",
    recommendedFoods: "推荐食物：",
    foodsToAvoid: "避免食物：",
    lifestyleRecommendations: "生活方式建议",
    exercise: "运动建议",
    acupoints: "穴位按摩",
    footer1: "本报告由 Sihat 中医AI助手生成，仅供参考。",
    footer2: "如需专业医疗建议，请咨询持证中医师。",
    fileName: "中医诊断报告",
  },
  ms: {
    title: "Laporan Diagnosis TCM",
    subtitle: "Analisis Perubatan Tradisional Cina",
    generated: "Dijana pada",
    mainDiagnosis: "DIAGNOSIS UTAMA",
    constitution: "Perlembagaan",
    detailedAnalysis: "ANALISIS TERPERINCI",
    dietaryRecommendations: "CADANGAN PEMAKANAN",
    recommendedFoods: "Makanan Disyorkan:",
    foodsToAvoid: "Makanan Perlu Dielakkan:",
    lifestyleRecommendations: "CADANGAN GAYA HIDUP",
    exercise: "CADANGAN SENAMAN",
    acupoints: "TITIK AKUPUNKTUR",
    footer1: "Laporan ini dijana oleh Pembantu AI Sihat TCM untuk tujuan maklumat sahaja.",
    footer2: "Sila rujuk pengamal TCM berlesen untuk nasihat perubatan profesional.",
    fileName: "Laporan_Diagnosis_TCM",
  },
};

// Helper function to safely extract string from various formats
export function extractString(val: any, fallback: string = ""): string {
  if (!val) return fallback;
  if (typeof val === "string") return val;
  if (typeof val === "object") {
    // Try common field names
    if (val.primary_pattern) return val.primary_pattern;
    if (val.type) return val.type;
    if (val.summary) return val.summary;
    // Convert object to readable format
    return Object.entries(val)
      .map(
        ([key, value]) =>
          `${key.replace(/_/g, " ")}: ${typeof value === "string" ? value : JSON.stringify(value)}`
      )
      .join("\n");
  }
  return String(val);
}

export const calculateBMI = (height?: number, weight?: number) => {
  if (!height || !weight) return null;
  const heightM = height / 100;
  return (weight / (heightM * heightM)).toFixed(1);
};

export const downloadPDF = async (
  language: "en" | "zh" | "ms",
  data: any,
  patientInfo: any,
  reportOptions: any,
  diagnosisText: string,
  constitutionText: string,
  analysisText: string,
  foodRecs: string[],
  avoidRecs: string[]
) => {
  const t = pdfTranslations[language];
  const doc = new jsPDF();

  // Add Chinese font if needed
  await addChineseFont(doc);
  const fontName = "NotoSansSC";

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPos = 20;

  // Helper function to add text with word wrap
  const addWrappedText = (text: string, fontSize: number, isBold = false) => {
    doc.setFontSize(fontSize);
    try {
      doc.setFont(fontName, "normal");
    } catch (e) {
      doc.setFont("helvetica", isBold ? "bold" : "normal");
    }
    const lines = doc.splitTextToSize(text, contentWidth);

    // Check if we need a new page
    if (yPos + lines.length * fontSize * 0.5 > 280) {
      doc.addPage();
      yPos = 20;
    }

    doc.text(lines, margin, yPos);
    yPos += lines.length * fontSize * 0.4 + 5;
  };

  // Title
  doc.setTextColor(6, 95, 70); // Emerald-800
  addWrappedText(t.title, 24, true);

  // Subtitle
  doc.setTextColor(87, 83, 78); // Stone-600
  addWrappedText(t.subtitle, 12);
  yPos += 5;

  // Date
  const dateLocale = language === "zh" ? "zh-CN" : language === "ms" ? "ms-MY" : "en-US";
  const date = new Date().toLocaleDateString(dateLocale, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  addWrappedText(`${t.generated}: ${date}`, 10);
  yPos += 10;

  // Separator line
  doc.setDrawColor(16, 185, 129); // Emerald-500
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 15;

  // Patient Info if available
  if (patientInfo) {
    doc.setTextColor(41, 37, 36);
    addWrappedText("PATIENT INFORMATION", 14, true);
    doc.setTextColor(68, 64, 60);
    if (reportOptions.includePatientName !== false && patientInfo.name)
      addWrappedText(`Name: ${patientInfo.name}`, 11);
    if (reportOptions.includePatientAge !== false && patientInfo.age)
      addWrappedText(`Age: ${patientInfo.age} years`, 11);
    if (reportOptions.includePatientGender !== false && patientInfo.gender)
      addWrappedText(`Gender: ${patientInfo.gender}`, 11);
    if (reportOptions.includePatientContact && patientInfo.contact)
      addWrappedText(`Contact: ${patientInfo.contact}`, 11);
    if (reportOptions.includePatientAddress && patientInfo.address)
      addWrappedText(`Address: ${patientInfo.address}`, 11);
    if (reportOptions.includeEmergencyContact && patientInfo.emergencyContact)
      addWrappedText(`Emergency Contact: ${patientInfo.emergencyContact}`, 11);
    if (reportOptions.includeBMI !== false && patientInfo.height && patientInfo.weight) {
      addWrappedText(`Height: ${patientInfo.height} cm | Weight: ${patientInfo.weight} kg`, 11);
      addWrappedText(`BMI: ${calculateBMI(patientInfo.height, patientInfo.weight)}`, 11);
    }
    yPos += 10;
  }

  // Main Diagnosis
  doc.setTextColor(6, 95, 70);
  addWrappedText(t.mainDiagnosis, 14, true);
  doc.setTextColor(20, 83, 45); // Emerald-900
  addWrappedText(diagnosisText, 16, true);

  doc.setTextColor(21, 128, 61); // Emerald-700
  addWrappedText(`${t.constitution}: ${constitutionText}`, 12);
  yPos += 10;

  // Detailed Analysis
  doc.setTextColor(41, 37, 36); // Stone-800
  addWrappedText(t.detailedAnalysis, 14, true);
  doc.setTextColor(68, 64, 60); // Stone-700
  addWrappedText(analysisText, 11);
  yPos += 10;

  // Dietary Recommendations
  if (foodRecs.length > 0 || avoidRecs.length > 0) {
    doc.setTextColor(41, 37, 36);
    addWrappedText(t.dietaryRecommendations, 14, true);

    if (foodRecs.length > 0) {
      doc.setTextColor(21, 128, 61);
      addWrappedText(t.recommendedFoods, 12, true);
      foodRecs.forEach((food: string) => {
        doc.setTextColor(68, 64, 60);
        addWrappedText(`• ${food}`, 11);
      });
      yPos += 5;
    }

    if (avoidRecs.length > 0) {
      doc.setTextColor(185, 28, 28); // Red-700
      addWrappedText(t.foodsToAvoid, 12, true);
      avoidRecs.forEach((food: string) => {
        doc.setTextColor(68, 64, 60);
        addWrappedText(`• ${food}`, 11);
      });
    }
    yPos += 10;
  }

  // Lifestyle Recommendations
  const lifestyleRecs = data.recommendations?.lifestyle || [];
  if (lifestyleRecs.length > 0) {
    doc.setTextColor(41, 37, 36);
    addWrappedText(t.lifestyleRecommendations, 14, true);
    lifestyleRecs.forEach((tip: string) => {
      doc.setTextColor(68, 64, 60);
      addWrappedText(`• ${tip}`, 11);
    });
    yPos += 15;
  }

  // Footer
  doc.setTextColor(120, 113, 108); // Stone-500
  doc.setFontSize(9);
  doc.text(t.footer1, margin, 280);
  doc.text(t.footer2, margin, 285);

  // Save the PDF
  const isoDate = new Date().toISOString().split("T")[0]; // YYYY-MM-DD
  const fileName = `${t.fileName}_${isoDate}.pdf`;
  doc.save(fileName);
};
