import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { createPortal } from "react-dom";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase/client";
import { useAuth } from "@/stores/useAppStore";
import { useDoctorLevel } from "@/stores/useAppStore";
import { useLanguage } from "@/stores/useAppStore";
import { Stethoscope, ArrowLeft } from "lucide-react";
import { jsPDF } from "jspdf";
import { addChineseFont } from "@/lib/chinese-font";
import { extractDiagnosisTitle, extractConstitutionType } from "@/lib/tcm-utils";

// Sub-components
import { ReportHeader } from "./report/ReportHeader";
import { ReportPatientInfo } from "./report/ReportPatientInfo";
import { ReportDiagnosisSection } from "./report/ReportDiagnosisSection";
import { ReportRecommendations } from "./report/ReportRecommendations";
import { ReportActions } from "./report/ReportActions";
import { PractitionerList } from "./report/PractitionerList";
import { ViewSwitcher, type ViewMode } from "./report/ViewSwitcher";
import { ReportChatWindow, ReportChatButton, type Message } from "./ReportChatWindow";
import { InfographicsGenerator } from "./InfographicsGenerator";
import { SaveToDashboardBanner } from "@/components/patient/SaveToDashboardBanner";

import type { DiagnosisReport } from "@/types/database";
import type { PDFPatientInfo, PDFReportOptions, PDFGenerationData } from "@/types/pdf";

// Interfaces
interface DiagnosisReportProps {
  data: DiagnosisReport | PDFGenerationData;
  patientInfo?: PDFPatientInfo;
  reportOptions?: PDFReportOptions;
  smartConnectData?: Record<string, unknown>;
  onRestart: () => void;
  saved?: boolean;
  isDoctorView?: boolean;
}

// Translations (Same as original)
const translations = {
  en: {
    title: "TCM Diagnosis Report",
    subtitle: "Traditional Chinese Medicine Analysis",
    generated: "Generated",
    mainDiagnosis: "MAIN DIAGNOSIS",
    constitution: "Constitution",
    detailedAnalysis: "DETAILED ANALYSIS",
    dietaryRecommendations: "DIETARY RECOMMENDATIONS",
    recommendedFoods: "Recommended Foods:",
    foodsToAvoid: "Foods to Avoid:",
    lifestyleRecommendations: "LIFESTYLE RECOMMENDATIONS",
    exercise: "EXERCISE SUGGESTIONS",
    acupoints: "ACUPOINTS",
    footer1: "This report is generated by Sihat TCM AI Assistant for informational purposes only.",
    footer2: "Please consult a licensed TCM practitioner for professional medical advice.",
    fileName: "TCM_Diagnosis",
    viewFullReport: "View Full Report",
    reportSummary: "TCM Report Summary",
    chatReference: "Reference while chatting",
    diagnosis: "Diagnosis",
  },
  zh: {
    title: "中医诊断报告",
    subtitle: "传统中医药分析",
    generated: "生成日期",
    mainDiagnosis: "主要诊断",
    constitution: "体质",
    detailedAnalysis: "详细分析",
    dietaryRecommendations: "饮食建议",
    recommendedFoods: "推荐食物：",
    foodsToAvoid: "避免食物：",
    lifestyleRecommendations: "生活方式建议",
    exercise: "运动建议",
    acupoints: "穴位按摩",
    footer1: "本报告由 Sihat 中医AI助手生成，仅供参考。",
    footer2: "如需专业医疗建议，请咨询持证中医师。",
    fileName: "中医诊断报告",
    viewFullReport: "查看完整报告",
    reportSummary: "中医报告摘要",
    chatReference: "对话时参考",
    diagnosis: "诊断",
  },
  ms: {
    title: "Laporan Diagnosis TCM",
    subtitle: "Analisis Perubatan Tradisional Cina",
    generated: "Dijana pada",
    mainDiagnosis: "DIAGNOSIS UTAMA",
    constitution: "Perlembagaan",
    detailedAnalysis: "ANALISIS TERPERINCI",
    dietaryRecommendations: "CADANGAN PEMAKANAN",
    recommendedFoods: "Makanan Disyorkan:",
    foodsToAvoid: "Makanan Perlu Dielakkan:",
    lifestyleRecommendations: "CADANGAN GAYA HIDUP",
    exercise: "CADANGAN SENAMAN",
    acupoints: "TITIK AKUPUNKTUR",
    footer1: "Laporan ini dijana oleh Pembantu AI Sihat TCM untuk tujuan maklumat sahaja.",
    footer2: "Sila rujuk pengamal TCM berlesen untuk nasihat perubatan profesional.",
    fileName: "Laporan_Diagnosis_TCM",
    viewFullReport: "Lihat Laporan Penuh",
    reportSummary: "Ringkasan Laporan TCM",
    chatReference: "Rujukan semasa bersembang",
    diagnosis: "Diagnosis",
  },
};

export function DiagnosisReport({
  data,
  patientInfo,
  reportOptions,
  smartConnectData,
  onRestart,
  saved,
  isDoctorView = false,
}: DiagnosisReportProps) {
  const { getDoctorInfo } = useDoctorLevel();
  const doctorInfo = getDoctorInfo();
  // @ts-ignore
  const { language } = useLanguage();
  const t = translations[language as keyof typeof translations];
  const { user, profile } = useAuth();
  const router = useRouter();
  const opts = reportOptions || {};

  // State
  const [viewMode, setViewMode] = useState<ViewMode>("modern");
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [isInfographicsOpen, setIsInfographicsOpen] = useState(false);
  const [activeQuestion, setActiveQuestion] = useState<string | null>(null);
  const [isChatExpanded, setIsChatExpanded] = useState(false);
  const [mounted, setMounted] = useState(false);
  const [chatMessages, setChatMessages] = useState<Message[]>([]);
  const [doctors, setDoctors] = useState<any[]>([]);
  const [loadingDoctors, setLoadingDoctors] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [hasSaved, setHasSaved] = useState(saved || false);

  useEffect(() => {
    const fetchDoctors = async () => {
      try {
        const { data } = await supabase.from("tcm_practitioners").select("*");
        if (data) {
          setDoctors(
            data.map((d: any) => ({
              id: d.id,
              name: d.name,
              photo: d.photo,
              clinicName: d.clinic_name,
              specialties: d.specialties || [],
              address: d.address,
              phone: d.phone,
              experience: d.experience,
              wazeLink: d.waze_link,
              workingHours: d.working_hours,
            }))
          );
        }
      } catch (error) {
        console.error("Error fetching doctors:", error);
      } finally {
        setLoadingDoctors(false);
      }
    };
    fetchDoctors();
    setMounted(true);
  }, []);

  // Animation Variants
  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1, delayChildren: 0.1 },
    },
  };

  const item = {
    hidden: { opacity: 0, y: 15, scale: 0.98 },
    show: {
      opacity: 1,
      y: 0,
      scale: 1,
      transition: { type: "spring", stiffness: 220, damping: 20 }
    },
  };

  // Process Data
  const diagnosisText = extractDiagnosisTitle(data.diagnosis);
  const constitutionText = extractConstitutionType(data.constitution);
  const analysisText =
    typeof data.analysis === "string" ? data.analysis : data.analysis?.summary || "";

  const getFoodRecommendations = () => {
    if (data.recommendations?.food_therapy?.beneficial)
      return data.recommendations.food_therapy.beneficial;
    return data.recommendations?.food || [];
  };

  const getFoodsToAvoid = () => {
    if (data.recommendations?.food_therapy?.avoid) return data.recommendations.food_therapy.avoid;
    return data.recommendations?.avoid || [];
  };

  const getRecipes = () => {
    return data.recommendations?.food_therapy?.recipes || [];
  };

  const handleSectionClick = (question: string) => {
    setActiveQuestion(question);
    setIsChatOpen(true);
  };

  // Actions
  const downloadPDF = async (languageKey = "en") => {
    const tPdf = translations[languageKey as keyof typeof translations];
    const doc = new jsPDF();
    await addChineseFont(doc);
    const fontName = "NotoSansSC";
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let yPos = 20;

    const addWrappedText = (text: string, fontSize: number, isBold = false) => {
      doc.setFontSize(fontSize);
      try {
        doc.setFont(fontName, "normal");
      } catch {
        doc.setFont("helvetica", isBold ? "bold" : "normal");
      }
      const lines = doc.splitTextToSize(text, contentWidth);
      if (yPos + lines.length * fontSize * 0.5 > 280) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(lines, margin, yPos);
      yPos += lines.length * fontSize * 0.4 + 5;
    };

    // Title
    doc.setTextColor(6, 95, 70);
    addWrappedText(tPdf.title, 24, true);
    doc.setTextColor(87, 83, 78);
    addWrappedText(tPdf.subtitle, 12);
    yPos += 5;

    const dateLocale = languageKey === "zh" ? "zh-CN" : languageKey === "ms" ? "ms-MY" : "en-US";
    const date = new Date().toLocaleDateString(dateLocale, {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    addWrappedText(`${tPdf.generated}: ${date}`, 10);
    yPos += 10;
    doc.setDrawColor(16, 185, 129);
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;

    // Main Diagnosis
    doc.setTextColor(6, 95, 70);
    addWrappedText(tPdf.mainDiagnosis, 14, true);
    doc.setTextColor(20, 83, 45);
    addWrappedText(diagnosisText, 16, true);
    doc.setTextColor(21, 128, 61);
    addWrappedText(`${tPdf.constitution}: ${constitutionText}`, 12);
    yPos += 10;
    doc.setTextColor(41, 37, 36);
    addWrappedText(tPdf.detailedAnalysis, 14, true);
    doc.setTextColor(68, 64, 60);
    addWrappedText(analysisText, 11);
    yPos += 10;

    // Save
    const isoDate = new Date().toISOString().split("T")[0];
    doc.save(`${tPdf.fileName}_${isoDate}.pdf`);
  };

  const shareReport = async () => {
    const shareText = `TCM Diagnosis: ${diagnosisText}\nConstitution: ${constitutionText}\n\nView Full Report at https://sihat-tcm.vercel.app`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: "TCM Report",
          text: shareText,
          url: "https://sihat-tcm.vercel.app",
        });
      } catch (e) {
        console.error(e);
      }
    } else {
      navigator.clipboard.writeText(shareText);
      alert(language === "zh" ? "报告链接已复制！" : "Report link copied!");
    }
  };

  const handleSaveToHistory = async () => {
    if (!user) {
      localStorage.setItem(
        "pendingDiagnosisSave",
        JSON.stringify({ data, patientInfo, reportOptions, smartConnectData })
      );
      router.push("/login?redirect=save-diagnosis");
      return;
    }
    setIsSaving(true);
    try {
      const reportWithProfile = {
        ...data,
        patient_profile: {
          name: patientInfo?.name,
          age: patientInfo?.age,
          gender: patientInfo?.gender,
          height: patientInfo?.height,
          weight: patientInfo?.weight,
        },
        saved_by_role: profile?.role || "patient",
        saved_at: new Date().toISOString(),
      };
      const { error } = await supabase.from("inquiries").insert({
        user_id: user.id,
        symptoms: patientInfo?.symptoms || "Not provided",
        diagnosis_report: reportWithProfile,
        created_at: new Date().toISOString(),
      });
      if (error) throw error;
      setHasSaved(true);
      alert(language === "zh" ? "已保存！" : "Saved!");
    } catch (error) {
      console.error(error);
      alert("Failed to save.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleRequestVerification = () => {
    alert(language === "zh" ? "请求已发送！" : "Request Sent!");
  };

  // Mobile Summary
  const MobileReportSummary = () => (
    <div className="bg-white/80 backdrop-blur-md p-4 border-b border-stone-200 z-50">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gradient-to-br from-emerald-100 to-teal-100 rounded-full flex items-center justify-center shadow-inner">
            <Stethoscope className="w-5 h-5 text-emerald-600" />
          </div>
          <div>
            <h3 className="font-semibold text-slate-800 text-sm">{t.reportSummary}</h3>
            <p className="text-xs text-slate-500">{t.chatReference}</p>
          </div>
        </div>
        <button
          onClick={() => setIsChatExpanded(false)}
          className="text-xs font-medium px-4 py-2 bg-slate-900 text-white rounded-full shadow-lg hover:shadow-xl hover:bg-slate-800 transition-all"
        >
          {t.viewFullReport}
        </button>
      </div>
      <div className="mt-3 bg-stone-50 rounded-xl p-3 border border-stone-100">
        <p className="text-xs text-stone-500 font-medium uppercase tracking-wider mb-1">{t.diagnosis}</p>
        <p className="text-sm font-semibold text-slate-800 line-clamp-2">{diagnosisText}</p>
      </div>
    </div>
  );

  const getBackgroundClass = () => {
    switch (viewMode) {
      case "classic": return "bg-[#F9F7F5]"; // Paper-like
      case "summary": return "bg-slate-50";
      default: return "bg-[#F2F2F7]"; // iOS System Gray 6
    }
  };

  const getContainerClass = () => {
    if (viewMode === "classic") return "max-w-4xl mx-auto bg-white shadow-sm border border-stone-200 min-h-screen my-8 p-12 print:p-0 print:m-0 print:border-none";
    if (viewMode === "summary") return "max-w-xl mx-auto py-8";
    return "max-w-4xl mx-auto pb-24 md:pb-12"; // Modern usually has generous padding
  };

  const content = (
    <div className={`min-h-screen transition-colors duration-500 ${getBackgroundClass()} ${isChatExpanded ? "fixed inset-0 z-50 flex flex-col md:flex-row overflow-hidden" : ""}`}>
      {/* Expanded Chat View (Mobile Overlay or Side-by-Side) */}
      {isChatExpanded && (
        <div className="md:hidden">
          <MobileReportSummary />
        </div>
      )}

      <motion.div
        variants={container}
        initial="hidden"
        animate="show"
        className={`w-full px-4 md:px-6 ${getContainerClass()} ${isChatExpanded ? "hidden md:block md:w-1/2 h-full overflow-y-auto p-6 scrollbar-hide border-r border-stone-200 !m-0 !max-w-none" : ""
          }`}
      >
        {!isChatExpanded && (
          <div className="py-6 flex justify-center sticky top-0 z-40 pointer-events-none">
            {/* Only show switcher if not expanded chat */}
            <div className="bg-white/50 backdrop-blur-xl rounded-full p-1 shadow-sm border border-white/20 pointer-events-auto">
              <ViewSwitcher currentMode={viewMode} onChange={setViewMode} />
            </div>
          </div>
        )}

        {/* Save to Dashboard Banner */}
        <div className="mb-6">
          <SaveToDashboardBanner
            isGuest={!user}
            isSaved={hasSaved}
            onViewDashboard={() => router.push("/patient")}
          />
        </div>

        {/* REPORT CONTENT */}
        <div className={`space-y-6 ${viewMode === "classic" ? "font-serif space-y-8" : ""}`}>

          <ReportHeader
            doctorInfo={doctorInfo}
            hasSaved={hasSaved}
            // @ts-ignore
            language={language}
            timestamp={data.timestamp}
            includeTimestamp={opts.includeTimestamp ?? true}
            variants={item}
            viewMode={viewMode}
          />

          {viewMode !== "summary" && (
            <ReportPatientInfo
              patientInfo={patientInfo}
              smartConnectData={smartConnectData}
              reportOptions={opts}
              variants={item}
              viewMode={viewMode}
            />
          )}

          <ReportDiagnosisSection
            data={data}
            diagnosisText={diagnosisText}
            constitutionText={constitutionText}
            analysisText={analysisText}
            variants={item}
            viewMode={viewMode}
          />

          {viewMode !== "summary" && (
            <ReportRecommendations
              data={data}
              reportOptions={opts}
              getFoodRecommendations={getFoodRecommendations}
              getFoodsToAvoid={getFoodsToAvoid}
              getRecipes={getRecipes}
              handleSectionClick={handleSectionClick}
              variants={item}
              viewMode={viewMode}
            />
          )}

          <motion.div variants={item}>
            <div className={`rounded-xl p-5 md:p-6 text-center ${viewMode === "classic" ? "bg-transparent italic text-stone-600 border-t border-stone-200 rounded-none" : "bg-white/60 backdrop-blur-sm border border-white/40"}`}>
              <p className="text-stone-500 text-sm md:text-base leading-relaxed">
                {data.disclaimer ||
                  "This report is generated by Sihat TCM AI Assistant for informational purposes only. It is not a substitute for professional medical advice. Please consult a licensed TCM practitioner for diagnosis and treatment."}
              </p>
            </div>
          </motion.div>

          {!isDoctorView && viewMode !== "summary" && (
            <motion.div variants={item}>
              <PractitionerList doctors={doctors} loading={loadingDoctors} variants={item} />
            </motion.div>
          )}

          <ReportActions
            onChatOpen={() => setIsChatOpen(true)}
            // @ts-ignore
            onDownloadPDF={() => downloadPDF(language)}
            onShare={shareReport}
            onSave={handleSaveToHistory}
            onRestart={onRestart}
            onInfographicsOpen={() => setIsInfographicsOpen(true)}
            onRequestVerification={handleRequestVerification}
            isSaving={isSaving}
            hasSaved={hasSaved}
            // @ts-ignore
            language={language}
            variants={item}
            isDoctorView={isDoctorView}
            viewMode={viewMode}
          />
        </div>

      </motion.div>

      {/* CHAT WINDOW HANDLING */}
      {isChatExpanded && (
        <div className="w-full md:w-1/2 flex-1 md:h-full bg-slate-50/50 backdrop-blur-3xl relative">
          <ReportChatWindow
            reportData={data}
            patientInfo={patientInfo}
            isOpen={true}
            onClose={() => setIsChatExpanded(false)}
            initialMessage={activeQuestion || undefined}
            onMessageSent={() => setActiveQuestion(null)}
            isExpanded={true}
            onToggleExpand={() => setIsChatExpanded(false)}
            messages={chatMessages}
            onMessagesChange={setChatMessages}
          />
        </div>
      )}

      {/* Floating Chat Bubble & Modal */}
      {!isChatExpanded && (
        <>
          <ReportChatButton onClick={() => setIsChatOpen(true)} />
          <ReportChatWindow
            reportData={data}
            patientInfo={patientInfo}
            isOpen={isChatOpen}
            onClose={() => setIsChatOpen(false)}
            initialMessage={activeQuestion || undefined}
            onMessageSent={() => setActiveQuestion(null)}
            isExpanded={false}
            onToggleExpand={() => {
              setIsChatOpen(false);
              setIsChatExpanded(true);
            }}
            messages={chatMessages}
            onMessagesChange={setChatMessages}
          />
        </>
      )}

      <InfographicsGenerator
        isOpen={isInfographicsOpen}
        onClose={() => setIsInfographicsOpen(false)}
        reportData={data}
        patientInfo={patientInfo}
      />
    </div>
  );

  if (isChatExpanded && mounted) {
    return createPortal(content, document.body);
  }

  return content;
}
