import { motion } from 'framer-motion'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Activity, Utensils, AlertCircle, HeartPulse, Leaf, Info, Download, Languages } from 'lucide-react'
import { jsPDF } from 'jspdf'
import { useDoctorLevel } from '@/contexts/DoctorContext'

type Language = 'en' | 'zh' | 'bm'

interface DiagnosisReportProps {
    data: {
        diagnosis: string;
        constitution: string;
        analysis: string;
        recommendations: {
            food: string[];
            avoid: string[];
            lifestyle: string[];
        };
    };
    onRestart: () => void;
}

// Language translations for PDF content
const translations = {
    en: {
        title: 'TCM Diagnosis Report',
        subtitle: 'Traditional Chinese Medicine Analysis',
        generated: 'Generated',
        mainDiagnosis: 'MAIN DIAGNOSIS',
        constitution: 'Constitution',
        detailedAnalysis: 'DETAILED ANALYSIS',
        dietaryRecommendations: 'DIETARY RECOMMENDATIONS',
        recommendedFoods: 'Recommended Foods:',
        foodsToAvoid: 'Foods to Avoid:',
        lifestyleRecommendations: 'LIFESTYLE RECOMMENDATIONS',
        footer1: 'This report is generated by Sihat TCM AI Assistant for informational purposes only.',
        footer2: 'Please consult a licensed TCM practitioner for professional medical advice.',
        fileName: 'TCM_Diagnosis'
    },
    zh: {
        title: '中医诊断报告',
        subtitle: '传统中医药分析',
        generated: '生成日期',
        mainDiagnosis: '主要诊断',
        constitution: '体质',
        detailedAnalysis: '详细分析',
        dietaryRecommendations: '饮食建议',
        recommendedFoods: '推荐食物：',
        foodsToAvoid: '避免食物：',
        lifestyleRecommendations: '生活方式建议',
        footer1: '本报告由 Sihat 中医AI助手生成，仅供参考。',
        footer2: '如需专业医疗建议，请咨询持证中医师。',
        fileName: '中医诊断报告'
    },
    bm: {
        title: 'Laporan Diagnosis TCM',
        subtitle: 'Analisis Perubatan Tradisional Cina',
        generated: 'Dijana pada',
        mainDiagnosis: 'DIAGNOSIS UTAMA',
        constitution: 'Perlembagaan',
        detailedAnalysis: 'ANALISIS TERPERINCI',
        dietaryRecommendations: 'CADANGAN PEMAKANAN',
        recommendedFoods: 'Makanan Disyorkan:',
        foodsToAvoid: 'Makanan Perlu Dielakkan:',
        lifestyleRecommendations: 'CADANGAN GAYA HIDUP',
        footer1: 'Laporan ini dijana oleh Pembantu AI Sihat TCM untuk tujuan maklumat sahaja.',
        footer2: 'Sila rujuk pengamal TCM berlesen untuk nasihat perubatan profesional.',
        fileName: 'Laporan_Diagnosis_TCM'
    }
}

export function DiagnosisReport({ data, onRestart }: DiagnosisReportProps) {
    const { getDoctorInfo } = useDoctorLevel()
    const doctorInfo = getDoctorInfo()

    const container = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1
            }
        }
    }

    const item = {
        hidden: { opacity: 0, y: 20 },
        show: { opacity: 1, y: 0 }
    }

    const downloadPDF = (language: Language = 'en') => {
        const t = translations[language]
        const doc = new jsPDF()
        const pageWidth = doc.internal.pageSize.getWidth()
        const margin = 20
        const contentWidth = pageWidth - margin * 2
        let yPos = 20

        // Helper function to add text with word wrap
        const addWrappedText = (text: string, fontSize: number, isBold = false) => {
            doc.setFontSize(fontSize)
            doc.setFont('helvetica', isBold ? 'bold' : 'normal')
            const lines = doc.splitTextToSize(text, contentWidth)

            // Check if we need a new page
            if (yPos + (lines.length * fontSize * 0.5) > 280) {
                doc.addPage()
                yPos = 20
            }

            doc.text(lines, margin, yPos)
            yPos += lines.length * fontSize * 0.4 + 5
        }

        // Title
        doc.setTextColor(6, 95, 70) // Emerald-800
        addWrappedText(t.title, 24, true)

        // Subtitle
        doc.setTextColor(87, 83, 78) // Stone-600
        addWrappedText(t.subtitle, 12)
        yPos += 5

        // Date
        const dateLocale = language === 'zh' ? 'zh-CN' : language === 'bm' ? 'ms-MY' : 'en-US'
        const date = new Date().toLocaleDateString(dateLocale, {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        })
        addWrappedText(`${t.generated}: ${date}`, 10)
        yPos += 10

        // Separator line
        doc.setDrawColor(16, 185, 129) // Emerald-500
        doc.setLineWidth(0.5)
        doc.line(margin, yPos, pageWidth - margin, yPos)
        yPos += 15

        // Main Diagnosis
        doc.setTextColor(6, 95, 70)
        addWrappedText(t.mainDiagnosis, 14, true)
        doc.setTextColor(20, 83, 45) // Emerald-900
        addWrappedText(data.diagnosis, 16, true)

        doc.setTextColor(21, 128, 61) // Emerald-700
        addWrappedText(`${t.constitution}: ${data.constitution}`, 12)
        yPos += 10

        // Detailed Analysis
        doc.setTextColor(41, 37, 36) // Stone-800
        addWrappedText(t.detailedAnalysis, 14, true)
        doc.setTextColor(68, 64, 60) // Stone-700
        addWrappedText(data.analysis, 11)
        yPos += 10

        // Dietary Recommendations
        doc.setTextColor(41, 37, 36)
        addWrappedText(t.dietaryRecommendations, 14, true)

        doc.setTextColor(21, 128, 61)
        addWrappedText(t.recommendedFoods, 12, true)
        data.recommendations.food.forEach((food) => {
            doc.setTextColor(68, 64, 60)
            addWrappedText(`• ${food}`, 11)
        })
        yPos += 5

        doc.setTextColor(185, 28, 28) // Red-700
        addWrappedText(t.foodsToAvoid, 12, true)
        data.recommendations.avoid.forEach((food) => {
            doc.setTextColor(68, 64, 60)
            addWrappedText(`• ${food}`, 11)
        })
        yPos += 10

        // Lifestyle Recommendations
        doc.setTextColor(41, 37, 36)
        addWrappedText(t.lifestyleRecommendations, 14, true)
        data.recommendations.lifestyle.forEach((tip) => {
            doc.setTextColor(68, 64, 60)
            addWrappedText(`• ${tip}`, 11)
        })
        yPos += 15

        // Footer
        doc.setTextColor(120, 113, 108) // Stone-500
        doc.setFontSize(9)
        doc.text(t.footer1, margin, 280)
        doc.text(t.footer2, margin, 285)

        // Save the PDF
        const isoDate = new Date().toISOString().split('T')[0] // YYYY-MM-DD
        const fileName = `${t.fileName}_${isoDate}.pdf`
        doc.save(fileName)
    }

    return (
        <motion.div
            variants={container}
            initial="hidden"
            animate="show"
            className="space-y-4 md:space-y-6 max-w-3xl mx-auto px-2 md:px-0"
        >
            {/* Header Section */}
            <motion.div variants={item} className="text-center space-y-1 md:space-y-2">
                <div className="flex items-center justify-center gap-2 mb-2">
                    <span className={`px-3 py-1 rounded-full text-sm font-medium border ${doctorInfo.bgColor} ${doctorInfo.borderColor} ${doctorInfo.textColor}`}>
                        {doctorInfo.icon} Analyzed by {doctorInfo.name}
                    </span>
                </div>
                <h2 className="text-2xl md:text-3xl font-bold text-emerald-900">Diagnosis Report</h2>
                <p className="text-stone-600 text-sm md:text-base">Based on your Wang, Wen, Wen, and Qie analysis</p>

                {doctorInfo.id === 'master' && (
                    <div className="max-w-md mx-auto mt-2 bg-amber-50 border border-amber-200 rounded-lg p-2 text-xs text-amber-800">
                        <p><strong>Master Level Analysis:</strong> This report includes deep TCM theoretical analysis and comprehensive constitution evaluation.</p>
                    </div>
                )}
            </motion.div>

            {/* Main Diagnosis Card */}
            <motion.div variants={item}>
                <Card className="border-emerald-100 bg-emerald-50/50">
                    <CardHeader className="pb-2 px-4 md:px-6">
                        <CardTitle className="flex items-center gap-2 text-emerald-800 text-base md:text-lg">
                            <Activity className="h-5 w-5" />
                            Main Diagnosis
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="px-4 md:px-6">
                        <div className="text-xl md:text-2xl font-semibold text-emerald-900 mb-1">
                            {data.diagnosis}
                        </div>
                        <div className="flex items-center gap-2 text-emerald-700 font-medium text-sm md:text-base">
                            <HeartPulse className="h-4 w-4" />
                            Constitution: {data.constitution}
                        </div>
                    </CardContent>
                </Card>
            </motion.div>

            {/* Detailed Analysis */}
            <motion.div variants={item}>
                <Card>
                    <CardHeader className="pb-2">
                        <CardTitle className="flex items-center gap-2 text-stone-800">
                            <Info className="h-5 w-5 text-stone-600" />
                            Detailed Analysis
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p className="text-stone-700 leading-relaxed whitespace-pre-wrap">
                            {data.analysis}
                        </p>
                    </CardContent>
                </Card>
            </motion.div>

            {/* Recommendations Grid - Stack on mobile */}
            <div className="grid md:grid-cols-2 gap-4 md:gap-6">
                {/* Food Recommendations */}
                <motion.div variants={item} className="space-y-6">
                    <Card className="h-full">
                        <CardHeader className="pb-2">
                            <CardTitle className="flex items-center gap-2 text-stone-800">
                                <Utensils className="h-5 w-5 text-orange-500" />
                                Dietary Advice
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div>
                                <h4 className="font-medium text-emerald-700 mb-2 flex items-center gap-2">
                                    <Leaf className="h-4 w-4" /> Recommended
                                </h4>
                                <ul className="list-disc list-inside text-stone-600 space-y-1 text-sm">
                                    {data.recommendations.food.map((food, idx) => (
                                        <li key={idx}>{food}</li>
                                    ))}
                                </ul>
                            </div>
                            <div>
                                <h4 className="font-medium text-red-700 mb-2 flex items-center gap-2">
                                    <AlertCircle className="h-4 w-4" /> Avoid
                                </h4>
                                <ul className="list-disc list-inside text-stone-600 space-y-1 text-sm">
                                    {data.recommendations.avoid.map((food, idx) => (
                                        <li key={idx}>{food}</li>
                                    ))}
                                </ul>
                            </div>
                        </CardContent>
                    </Card>
                </motion.div>

                {/* Lifestyle Advice */}
                <motion.div variants={item}>
                    <Card className="h-full">
                        <CardHeader className="pb-2">
                            <CardTitle className="flex items-center gap-2 text-stone-800">
                                <Leaf className="h-5 w-5 text-green-600" />
                                Lifestyle
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <ul className="space-y-3">
                                {data.recommendations.lifestyle.map((tip, idx) => (
                                    <li key={idx} className="flex gap-3 text-stone-600 text-sm">
                                        <div className="h-1.5 w-1.5 rounded-full bg-emerald-400 mt-2 shrink-0" />
                                        <span>{tip}</span>
                                    </li>
                                ))}
                            </ul>
                        </CardContent>
                    </Card>
                </motion.div>
            </div>

            {/* Action Buttons - Better mobile layout */}
            <motion.div variants={item} className="flex flex-col sm:flex-row flex-wrap justify-center gap-3 pt-4 md:pt-6">
                {/* Language Download Buttons */}
                <div className="flex flex-wrap justify-center gap-2 sm:gap-3">
                    <button
                        onClick={() => downloadPDF('en')}
                        className="px-4 py-2.5 bg-white border-2 border-emerald-600 text-emerald-600 rounded-full hover:bg-emerald-50 transition-colors shadow-md hover:shadow-lg flex items-center gap-2 text-sm font-medium min-h-[44px]"
                    >
                        <Download className="h-4 w-4" />
                        PDF (EN)
                    </button>
                    <button
                        onClick={() => downloadPDF('zh')}
                        className="px-4 py-2.5 bg-white border-2 border-amber-600 text-amber-600 rounded-full hover:bg-amber-50 transition-colors shadow-md hover:shadow-lg flex items-center gap-2 text-sm font-medium min-h-[44px]"
                    >
                        <Download className="h-4 w-4" />
                        PDF (中文)
                    </button>
                    <button
                        onClick={() => downloadPDF('bm')}
                        className="px-4 py-2.5 bg-white border-2 border-blue-600 text-blue-600 rounded-full hover:bg-blue-50 transition-colors shadow-md hover:shadow-lg flex items-center gap-2 text-sm font-medium min-h-[44px]"
                    >
                        <Download className="h-4 w-4" />
                        PDF (BM)
                    </button>
                </div>
                <button
                    onClick={onRestart}
                    className="w-full sm:w-auto px-6 py-2.5 bg-emerald-600 text-white rounded-full hover:bg-emerald-700 transition-colors shadow-lg hover:shadow-xl text-sm font-medium min-h-[44px]"
                >
                    Start New Consultation
                </button>
            </motion.div>
        </motion.div>
    )
}
