import { motion } from 'framer-motion'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Activity, Utensils, AlertCircle, HeartPulse, Leaf, Info, Download } from 'lucide-react'
import { jsPDF } from 'jspdf'

interface DiagnosisReportProps {
    data: {
        diagnosis: string;
        constitution: string;
        analysis: string;
        recommendations: {
            food: string[];
            avoid: string[];
            lifestyle: string[];
        };
    };
    onRestart: () => void;
}

export function DiagnosisReport({ data, onRestart }: DiagnosisReportProps) {
    const container = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1
            }
        }
    }

    const item = {
        hidden: { opacity: 0, y: 20 },
        show: { opacity: 1, y: 0 }
    }

    const downloadPDF = () => {
        const doc = new jsPDF()
        const pageWidth = doc.internal.pageSize.getWidth()
        const margin = 20
        const contentWidth = pageWidth - margin * 2
        let yPos = 20

        // Helper function to add text with word wrap
        const addWrappedText = (text: string, fontSize: number, isBold = false) => {
            doc.setFontSize(fontSize)
            doc.setFont('helvetica', isBold ? 'bold' : 'normal')
            const lines = doc.splitTextToSize(text, contentWidth)

            // Check if we need a new page
            if (yPos + (lines.length * fontSize * 0.5) > 280) {
                doc.addPage()
                yPos = 20
            }

            doc.text(lines, margin, yPos)
            yPos += lines.length * fontSize * 0.4 + 5
        }

        // Title
        doc.setTextColor(6, 95, 70) // Emerald-800
        addWrappedText('TCM Diagnosis Report', 24, true)

        // Subtitle
        doc.setTextColor(87, 83, 78) // Stone-600
        addWrappedText('Traditional Chinese Medicine Analysis', 12)
        yPos += 5

        // Date
        const date = new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        })
        addWrappedText(`Generated: ${date}`, 10)
        yPos += 10

        // Separator line
        doc.setDrawColor(16, 185, 129) // Emerald-500
        doc.setLineWidth(0.5)
        doc.line(margin, yPos, pageWidth - margin, yPos)
        yPos += 15

        // Main Diagnosis
        doc.setTextColor(6, 95, 70)
        addWrappedText('MAIN DIAGNOSIS', 14, true)
        doc.setTextColor(20, 83, 45) // Emerald-900
        addWrappedText(data.diagnosis, 16, true)

        doc.setTextColor(21, 128, 61) // Emerald-700
        addWrappedText(`Constitution: ${data.constitution}`, 12)
        yPos += 10

        // Detailed Analysis
        doc.setTextColor(41, 37, 36) // Stone-800
        addWrappedText('DETAILED ANALYSIS', 14, true)
        doc.setTextColor(68, 64, 60) // Stone-700
        addWrappedText(data.analysis, 11)
        yPos += 10

        // Dietary Recommendations
        doc.setTextColor(41, 37, 36)
        addWrappedText('DIETARY RECOMMENDATIONS', 14, true)

        doc.setTextColor(21, 128, 61)
        addWrappedText('Recommended Foods:', 12, true)
        data.recommendations.food.forEach((food) => {
            doc.setTextColor(68, 64, 60)
            addWrappedText(`• ${food}`, 11)
        })
        yPos += 5

        doc.setTextColor(185, 28, 28) // Red-700
        addWrappedText('Foods to Avoid:', 12, true)
        data.recommendations.avoid.forEach((food) => {
            doc.setTextColor(68, 64, 60)
            addWrappedText(`• ${food}`, 11)
        })
        yPos += 10

        // Lifestyle Recommendations
        doc.setTextColor(41, 37, 36)
        addWrappedText('LIFESTYLE RECOMMENDATIONS', 14, true)
        data.recommendations.lifestyle.forEach((tip) => {
            doc.setTextColor(68, 64, 60)
            addWrappedText(`• ${tip}`, 11)
        })
        yPos += 15

        // Footer
        doc.setTextColor(120, 113, 108) // Stone-500
        doc.setFontSize(9)
        doc.text(
            'This report is generated by Sihat TCM AI Assistant for informational purposes only.',
            margin,
            280
        )
        doc.text(
            'Please consult a licensed TCM practitioner for professional medical advice.',
            margin,
            285
        )

        // Save the PDF
        const fileName = `TCM_Diagnosis_${date.replace(/,?\s+/g, '_')}.pdf`
        doc.save(fileName)
    }

    return (
        <motion.div
            variants={container}
            initial="hidden"
            animate="show"
            className="space-y-6 max-w-3xl mx-auto"
        >
            {/* Header Section */}
            <motion.div variants={item} className="text-center space-y-2">
                <h2 className="text-3xl font-bold text-emerald-900">Diagnosis Report</h2>
                <p className="text-stone-600">Based on your Wang, Wen, Wen, and Qie analysis</p>
            </motion.div>

            {/* Main Diagnosis Card */}
            <motion.div variants={item}>
                <Card className="border-emerald-100 bg-emerald-50/50">
                    <CardHeader className="pb-2">
                        <CardTitle className="flex items-center gap-2 text-emerald-800">
                            <Activity className="h-5 w-5" />
                            Main Diagnosis
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-semibold text-emerald-900 mb-1">
                            {data.diagnosis}
                        </div>
                        <div className="flex items-center gap-2 text-emerald-700 font-medium">
                            <HeartPulse className="h-4 w-4" />
                            Constitution: {data.constitution}
                        </div>
                    </CardContent>
                </Card>
            </motion.div>

            {/* Detailed Analysis */}
            <motion.div variants={item}>
                <Card>
                    <CardHeader className="pb-2">
                        <CardTitle className="flex items-center gap-2 text-stone-800">
                            <Info className="h-5 w-5 text-stone-600" />
                            Detailed Analysis
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p className="text-stone-700 leading-relaxed whitespace-pre-wrap">
                            {data.analysis}
                        </p>
                    </CardContent>
                </Card>
            </motion.div>

            {/* Recommendations Grid */}
            <div className="grid md:grid-cols-2 gap-6">
                {/* Food Recommendations */}
                <motion.div variants={item} className="space-y-6">
                    <Card className="h-full">
                        <CardHeader className="pb-2">
                            <CardTitle className="flex items-center gap-2 text-stone-800">
                                <Utensils className="h-5 w-5 text-orange-500" />
                                Dietary Advice
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div>
                                <h4 className="font-medium text-emerald-700 mb-2 flex items-center gap-2">
                                    <Leaf className="h-4 w-4" /> Recommended
                                </h4>
                                <ul className="list-disc list-inside text-stone-600 space-y-1 text-sm">
                                    {data.recommendations.food.map((food, idx) => (
                                        <li key={idx}>{food}</li>
                                    ))}
                                </ul>
                            </div>
                            <div>
                                <h4 className="font-medium text-red-700 mb-2 flex items-center gap-2">
                                    <AlertCircle className="h-4 w-4" /> Avoid
                                </h4>
                                <ul className="list-disc list-inside text-stone-600 space-y-1 text-sm">
                                    {data.recommendations.avoid.map((food, idx) => (
                                        <li key={idx}>{food}</li>
                                    ))}
                                </ul>
                            </div>
                        </CardContent>
                    </Card>
                </motion.div>

                {/* Lifestyle Advice */}
                <motion.div variants={item}>
                    <Card className="h-full">
                        <CardHeader className="pb-2">
                            <CardTitle className="flex items-center gap-2 text-stone-800">
                                <Leaf className="h-5 w-5 text-green-600" />
                                Lifestyle
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <ul className="space-y-3">
                                {data.recommendations.lifestyle.map((tip, idx) => (
                                    <li key={idx} className="flex gap-3 text-stone-600 text-sm">
                                        <div className="h-1.5 w-1.5 rounded-full bg-emerald-400 mt-2 shrink-0" />
                                        <span>{tip}</span>
                                    </li>
                                ))}
                            </ul>
                        </CardContent>
                    </Card>
                </motion.div>
            </div>

            {/* Action Buttons */}
            <motion.div variants={item} className="flex justify-center gap-4 pt-6">
                <button
                    onClick={downloadPDF}
                    className="px-6 py-2 bg-white border-2 border-emerald-600 text-emerald-600 rounded-full hover:bg-emerald-50 transition-colors shadow-lg hover:shadow-xl flex items-center gap-2"
                >
                    <Download className="h-4 w-4" />
                    Download PDF
                </button>
                <button
                    onClick={onRestart}
                    className="px-6 py-2 bg-emerald-600 text-white rounded-full hover:bg-emerald-700 transition-colors shadow-lg hover:shadow-xl"
                >
                    Start New Consultation
                </button>
            </motion.div>
        </motion.div>
    )
}
