/**
 * ViewReportScreen - View Medical Report Screen
 * 
 * Displays a saved diagnosis report with markdown rendering,
 * share functionality, and native-first UX with glassmorphism.
 */

import React, { useState, useRef, useEffect } from 'react';
import {
    View,
    Text,
    StyleSheet,
    ScrollView,
    TouchableOpacity,
    Share,
    Animated,
    SafeAreaView,
    Platform,
    StatusBar,
    ActivityIndicator,
    Dimensions,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { BlurView } from 'expo-blur';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import Markdown from 'react-native-markdown-display';
import { useTheme } from '../contexts/ThemeContext';
import { useLanguage } from '../contexts/LanguageContext';

const { width } = Dimensions.get('window');

/**
 * ViewReportScreen Component
 * 
 * @param {Object} props
 * @param {Object} props.reportData - The report data to display
 * @param {string} props.reportData.reportName - Name/title of the report
 * @param {string} props.reportData.reportContent - Markdown content of the report
 * @param {string} props.reportData.createdAt - ISO date string
 * @param {Function} props.onBack - Callback to navigate back
 */
export default function ViewReportScreen({ reportData, onBack }) {
    const { theme, isDark } = useTheme();
    const { t } = useLanguage();
    const [isSharing, setIsSharing] = useState(false);

    // Animation values
    const fadeAnim = useRef(new Animated.Value(0)).current;
    const slideAnim = useRef(new Animated.Value(30)).current;

    // Play entry animation
    useEffect(() => {
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

        Animated.parallel([
            Animated.timing(fadeAnim, {
                toValue: 1,
                duration: 300,
                useNativeDriver: true,
            }),
            Animated.spring(slideAnim, {
                toValue: 0,
                tension: 50,
                friction: 8,
                useNativeDriver: true,
            }),
        ]).start();
    }, []);

    // Handle back navigation
    const handleBack = () => {
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
        onBack();
    };

    // Handle share
    const handleShare = async () => {
        if (isSharing) return;

        setIsSharing(true);
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);

        try {
            const reportName = reportData?.reportName || t.report?.title || 'TCM Diagnosis Report';
            const content = reportData?.reportContent || '';
            const createdAt = reportData?.createdAt
                ? new Date(reportData.createdAt).toLocaleDateString()
                : new Date().toLocaleDateString();

            const shareText = `📋 ${reportName}\n📅 ${createdAt}\n\n${content}\n\n━━━━━━━━━━━━━━━\n🌿 Generated by Sihat TCM`;

            await Share.share({
                message: shareText,
                title: reportName,
            });

            Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
        } catch (error) {
            console.error('Share error:', error);
            Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
        } finally {
            setIsSharing(false);
        }
    };

    // Format date for display
    const formatDate = (dateString) => {
        if (!dateString) return '';
        const date = new Date(dateString);
        return date.toLocaleDateString('en-US', {
            weekday: 'short',
            month: 'short',
            day: 'numeric',
            year: 'numeric',
        });
    };

    // Markdown styles
    const markdownStyles = {
        body: {
            color: theme.text.primary,
            fontSize: 15,
            lineHeight: 24,
        },
        heading1: {
            color: theme.text.primary,
            fontSize: 24,
            fontWeight: '700',
            marginTop: 20,
            marginBottom: 12,
            borderBottomWidth: 1,
            borderBottomColor: theme.border.default,
            paddingBottom: 8,
        },
        heading2: {
            color: theme.text.primary,
            fontSize: 20,
            fontWeight: '600',
            marginTop: 18,
            marginBottom: 10,
        },
        heading3: {
            color: theme.text.primary,
            fontSize: 17,
            fontWeight: '600',
            marginTop: 14,
            marginBottom: 8,
        },
        paragraph: {
            color: theme.text.secondary,
            fontSize: 15,
            lineHeight: 24,
            marginBottom: 12,
        },
        strong: {
            color: theme.text.primary,
            fontWeight: '600',
        },
        em: {
            fontStyle: 'italic',
        },
        bullet_list: {
            marginVertical: 8,
        },
        ordered_list: {
            marginVertical: 8,
        },
        list_item: {
            marginVertical: 4,
        },
        bullet_list_icon: {
            color: theme.accent.primary,
            marginRight: 8,
        },
        hr: {
            backgroundColor: theme.border.default,
            height: 1,
            marginVertical: 16,
        },
        blockquote: {
            backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.03)',
            borderLeftColor: theme.accent.primary,
            borderLeftWidth: 4,
            paddingLeft: 12,
            paddingVertical: 8,
            marginVertical: 12,
        },
        code_inline: {
            backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
            color: theme.accent.primary,
            paddingHorizontal: 6,
            paddingVertical: 2,
            borderRadius: 4,
            fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
            fontSize: 13,
        },
        code_block: {
            backgroundColor: isDark ? 'rgba(0,0,0,0.3)' : 'rgba(0,0,0,0.05)',
            padding: 12,
            borderRadius: 8,
            marginVertical: 12,
        },
        fence: {
            backgroundColor: isDark ? 'rgba(0,0,0,0.3)' : 'rgba(0,0,0,0.05)',
            padding: 12,
            borderRadius: 8,
            marginVertical: 12,
        },
        table: {
            borderWidth: 1,
            borderColor: theme.border.default,
            borderRadius: 8,
            marginVertical: 12,
        },
        thead: {
            backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.03)',
        },
        th: {
            padding: 10,
            fontWeight: '600',
            color: theme.text.primary,
            borderBottomWidth: 1,
            borderBottomColor: theme.border.default,
        },
        tr: {
            borderBottomWidth: 1,
            borderBottomColor: theme.border.subtle,
        },
        td: {
            padding: 10,
            color: theme.text.secondary,
        },
        link: {
            color: theme.accent.primary,
            textDecorationLine: 'underline',
        },
    };

    // Empty state
    if (!reportData || !reportData.reportContent) {
        return (
            <SafeAreaView style={[styles.container, { backgroundColor: theme.background.base }]}>
                <StatusBar barStyle={isDark ? 'light-content' : 'dark-content'} />

                {/* Header */}
                <View style={[styles.header, { borderBottomColor: theme.border.default }]}>
                    <TouchableOpacity
                        style={styles.backButton}
                        onPress={handleBack}
                        hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}
                    >
                        <Ionicons name="arrow-back" size={24} color={theme.text.primary} />
                    </TouchableOpacity>
                    <Text style={[styles.headerTitle, { color: theme.text.primary }]}>
                        {t.history?.viewReport || 'View Report'}
                    </Text>
                    <View style={styles.headerSpacer} />
                </View>

                {/* Empty State */}
                <View style={styles.emptyState}>
                    <Ionicons name="document-text-outline" size={64} color={theme.text.tertiary} />
                    <Text style={[styles.emptyTitle, { color: theme.text.secondary }]}>
                        {t.history?.noRecords || 'No report to display'}
                    </Text>
                    <TouchableOpacity
                        style={[styles.emptyButton, { backgroundColor: theme.accent.primary }]}
                        onPress={handleBack}
                    >
                        <Text style={styles.emptyButtonText}>
                            {t.common?.back || 'Go Back'}
                        </Text>
                    </TouchableOpacity>
                </View>
            </SafeAreaView>
        );
    }

    return (
        <SafeAreaView style={[styles.container, { backgroundColor: theme.background.base }]}>
            <StatusBar barStyle={isDark ? 'light-content' : 'dark-content'} />

            {/* Glassmorphism Header */}
            <BlurView
                intensity={isDark ? 40 : 80}
                tint={isDark ? 'dark' : 'light'}
                style={styles.headerBlur}
            >
                <LinearGradient
                    colors={isDark
                        ? ['rgba(16,185,129,0.1)', 'rgba(5,150,105,0.05)']
                        : ['rgba(255,255,255,0.9)', 'rgba(255,255,255,0.7)']}
                    style={styles.headerGradient}
                >
                    <View style={[styles.header, { borderBottomColor: theme.border.subtle }]}>
                        {/* Back Button */}
                        <TouchableOpacity
                            style={styles.backButton}
                            onPress={handleBack}
                            hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}
                        >
                            <Ionicons name="arrow-back" size={24} color={theme.text.primary} />
                        </TouchableOpacity>

                        {/* Title Section */}
                        <View style={styles.headerCenter}>
                            <Text
                                style={[styles.headerTitle, { color: theme.text.primary }]}
                                numberOfLines={1}
                            >
                                {reportData.reportName || t.report?.title || 'Diagnosis Report'}
                            </Text>
                            {reportData.createdAt && (
                                <Text style={[styles.headerSubtitle, { color: theme.text.tertiary }]}>
                                    {formatDate(reportData.createdAt)}
                                </Text>
                            )}
                        </View>

                        {/* Share Button */}
                        <TouchableOpacity
                            style={[
                                styles.shareButton,
                                { backgroundColor: `${theme.accent.primary}15` }
                            ]}
                            onPress={handleShare}
                            disabled={isSharing}
                            hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
                        >
                            {isSharing ? (
                                <ActivityIndicator size="small" color={theme.accent.primary} />
                            ) : (
                                <Ionicons name="share-outline" size={22} color={theme.accent.primary} />
                            )}
                        </TouchableOpacity>
                    </View>
                </LinearGradient>
            </BlurView>

            {/* Content */}
            <Animated.View
                style={[
                    styles.contentWrapper,
                    {
                        opacity: fadeAnim,
                        transform: [{ translateY: slideAnim }]
                    }
                ]}
            >
                <ScrollView
                    style={styles.scrollView}
                    contentContainerStyle={styles.scrollContent}
                    showsVerticalScrollIndicator={false}
                >
                    {/* Report Card */}
                    <View style={[
                        styles.reportCard,
                        {
                            backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(255,255,255,0.9)',
                            borderColor: theme.border.default,
                        }
                    ]}>
                        <Markdown style={markdownStyles}>
                            {reportData.reportContent}
                        </Markdown>
                    </View>

                    {/* Footer Disclaimer */}
                    <View style={styles.disclaimer}>
                        <Ionicons name="information-circle-outline" size={16} color={theme.text.tertiary} />
                        <Text style={[styles.disclaimerText, { color: theme.text.tertiary }]}>
                            {t.report?.disclaimer || 'This report is for reference only. Please consult a licensed TCM practitioner.'}
                        </Text>
                    </View>

                    {/* Bottom Padding */}
                    <View style={{ height: 40 }} />
                </ScrollView>
            </Animated.View>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    headerBlur: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 100,
    },
    headerGradient: {
        paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        minHeight: 56,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerCenter: {
        flex: 1,
        alignItems: 'center',
        marginHorizontal: 8,
    },
    headerTitle: {
        fontSize: 17,
        fontWeight: '600',
        textAlign: 'center',
    },
    headerSubtitle: {
        fontSize: 12,
        marginTop: 2,
    },
    headerSpacer: {
        width: 40,
    },
    shareButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    contentWrapper: {
        flex: 1,
        paddingTop: Platform.OS === 'ios' ? 90 : 80 + (StatusBar.currentHeight || 0),
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingTop: 16,
    },
    reportCard: {
        borderRadius: 16,
        borderWidth: 1,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    disclaimer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginTop: 16,
        paddingHorizontal: 8,
    },
    disclaimerText: {
        flex: 1,
        fontSize: 12,
        lineHeight: 18,
        marginLeft: 8,
    },
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 32,
    },
    emptyTitle: {
        fontSize: 17,
        marginTop: 16,
        textAlign: 'center',
    },
    emptyButton: {
        marginTop: 24,
        paddingHorizontal: 32,
        paddingVertical: 14,
        borderRadius: 12,
    },
    emptyButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 15,
    },
});
