/**
 * Results Helpers
 * Utility functions for the results/report screens
 */

/**
 * Helper to extract string from various data formats
 * @param {any} val - Value to extract string from
 * @param {string} fallback - Fallback value if extraction fails
 * @returns {string} Extracted string value
 */
export function extractString(val, fallback = '') {
    if (!val) return fallback;
    if (typeof val === 'string') return val;
    if (typeof val === 'object') {
        if (val.primary_pattern) return val.primary_pattern;
        if (val.type) return val.type;
        if (val.summary) return val.summary;
        return Object.entries(val)
            .map(([key, value]) => `${key.replace(/_/g, ' ')}: ${typeof value === 'string' ? value : JSON.stringify(value)}`)
            .join('\n');
    }
    return String(val);
}

/**
 * Calculate BMI from height and weight
 * @param {number|string} height - Height in cm
 * @param {number|string} weight - Weight in kg
 * @returns {string|null} Calculated BMI or null if invalid
 */
export function calculateBMI(height, weight) {
    if (!height || !weight) return null;
    const heightM = parseFloat(height) / 100;
    const weightNum = parseFloat(weight);
    if (heightM > 0 && weightNum > 0) {
        return (weightNum / (heightM * heightM)).toFixed(1);
    }
    return null;
}

/**
 * Format share text for diagnosis report
 * @param {Object} reportData - The report data object
 * @param {Object} constitution - The constitution object
 * @returns {string} Formatted share text
 */
export function formatShareText(reportData, constitution) {
    const diagnosis = reportData?.diagnosis?.primary_pattern || constitution.type;
    const foods = reportData?.recommendations?.food?.slice(0, 5).join(', ') || '';
    const avoid = reportData?.recommendations?.avoid?.slice(0, 3).join(', ') || '';

    return `📋 TCM Diagnosis Report
━━━━━━━━━━━━━━━━━
🏥 Diagnosis: ${diagnosis}
💪 Constitution: ${constitution.type}

${constitution.description}

🥗 Recommended Foods:
${foods}

🚫 Foods to Avoid:
${avoid}

━━━━━━━━━━━━━━━━━
🌿 Generated by Sihat TCM`;
}
