/**
 * Onboarding Configuration and Text
 */

export const COLORS = {
    emeraldDeep: '#064E3B',
    emeraldDark: '#065F46',
    emeraldMedium: '#10B981',
    amberStart: '#F59E0B',
    amberEnd: '#D97706',
    white: '#FFFFFF',
    textSecondary: 'rgba(255,255,255,0.7)',
    textTertiary: 'rgba(255,255,255,0.5)',
};

export const SLIDES = [
    {
        id: '1',
        titleKey: 'multiModal',
        subtitleKey: 'multiModalSub',
        icons: ['eye-outline', 'hand-left-outline', 'ear-outline'],
        iconLabels: ['tongueLabel', 'pulseLabel', 'voiceLabel'],
        trustBadge: 'chatGptCant',
    },
    {
        id: '2',
        icon: 'shield-checkmark-outline',
        titleKey: 'realDoctors',
        subtitleKey: 'realDoctorsSub',
        bulletPoints: ['doctorReview', 'guidedQuestions', 'notScraped'],
        badgeIcon: 'medical-outline',
        badgeTextKey: 'practitionerBacked',
    },
    {
        id: '3',
        icon: 'clipboard-outline',
        titleKey: 'triage',
        subtitleKey: 'triageSub',
        features: ['triageFeature', 'reportFeature', 'saveFeature'],
        featureIcons: ['help-circle-outline', 'share-social-outline', 'wallet-outline'],
    },
    {
        id: '4',
        icon: 'rocket-outline',
        titleKey: 'getStarted',
        subtitleKey: 'getStartedSub',
        isLanguageSlide: true,
    },
];

export const ONBOARDING_TEXT = {
    en: {
        multiModal: 'See What ChatGPT Can\'t',
        multiModalSub: 'AI-powered diagnosis using your tongue, pulse, and voice — not just text',
        chatGptCant: 'Beyond Text Chat',
        tongueLabel: 'Tongue',
        pulseLabel: 'Pulse',
        voiceLabel: 'Voice',
        realDoctors: 'Real Doctors. Real Trust.',
        realDoctorsSub: 'Unlike generic AI, we\'re built WITH TCM practitioners',
        doctorReview: '✓ Real TCM doctors review edge cases',
        guidedQuestions: '✓ Guided questions prevent confusion',
        notScraped: '✓ Not scraped from random internet sources',
        practitionerBacked: 'Practitioner-Backed AI',
        triage: '"Is This Serious?"',
        triageSub: 'Get instant clarity before your clinic visit',
        triageFeature: 'AI triage in seconds',
        reportFeature: 'Shareable health reports',
        saveFeature: 'Save RM100+ per visit',
        getStarted: 'Ready to Begin?',
        getStartedSub: 'Choose your preferred language',
        skip: 'Skip',
        next: 'Next',
        start: 'Start My Diagnosis',
    },
    zh: {
        multiModal: 'ChatGPT做不到的',
        multiModalSub: 'AI智能诊断——通过舌象、脉象和声音，不仅仅是文字',
        chatGptCant: '超越文字聊天',
        tongueLabel: '舌象',
        pulseLabel: '脉象',
        voiceLabel: '声音',
        realDoctors: '真正的医生，真正的信任',
        realDoctorsSub: '与普通AI不同，我们与中医师共同打造',
        doctorReview: '✓ 真正中医师审核疑难病例',
        guidedQuestions: '✓ 引导式问诊避免遗漏',
        notScraped: '✓ 非网络随意抓取资料',
        practitionerBacked: '中医师支持的AI',
        triage: '"这严重吗？"',
        triageSub: '就诊前获得即时分诊建议',
        triageFeature: '秒级AI分诊',
        reportFeature: '可分享健康报告',
        saveFeature: '每次省下RM100+',
        getStarted: '准备好了吗？',
        getStartedSub: '选择您的首选语言',
        skip: '跳过',
        next: '下一步',
        start: '开始我的诊断',
    },
    ms: {
        multiModal: 'Apa ChatGPT Tak Boleh',
        multiModalSub: 'Diagnosis AI menggunakan lidah, nadi, dan suara — bukan sekadar teks',
        chatGptCant: 'Melangkaui Sembang Teks',
        tongueLabel: 'Lidah',
        pulseLabel: 'Nadi',
        voiceLabel: 'Suara',
        realDoctors: 'Doktor Sebenar. Kepercayaan Sebenar.',
        realDoctorsSub: 'Tidak seperti AI biasa, kami dibina BERSAMA pengamal TCM',
        doctorReview: '✓ Doktor TCM sebenar menyemak kes sukar',
        guidedQuestions: '✓ Soalan berpandu elak kekeliruan',
        notScraped: '✓ Bukan dari sumber internet rawak',
        practitionerBacked: 'AI Disokong Pengamal',
        triage: '"Adakah Ini Serius?"',
        triageSub: 'Dapatkan kejelasan segera sebelum lawatan klinik',
        triageFeature: 'Triaj AI dalam saat',
        reportFeature: 'Laporan kesihatan boleh kongsi',
        saveFeature: 'Jimat RM100+ setiap lawatan',
        getStarted: 'Sedia Bermula?',
        getStartedSub: 'Pilih bahasa pilihan anda',
        skip: 'Langkau',
        next: 'Seterusnya',
        start: 'Mula Diagnosis Saya',
    },
};

export const LANGUAGE_OPTIONS = [
    { code: 'en', flag: '🇺🇸', name: 'English' },
    { code: 'zh', flag: '🇨🇳', name: '中文' },
    { code: 'ms', flag: '🇲🇾', name: 'Bahasa Malaysia' },
];
