-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- 1. Create profiles table (extends auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  role text check (role in ('patient', 'doctor', 'admin', 'developer')) default 'patient',
  full_name text,
  age int,
  gender text,
  height float,
  weight float,
  bmi float,
  medical_history text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- 2. Create system_prompts table
create table if not exists public.system_prompts (
  id bigint generated by default as identity primary key,
  role text unique not null,
  prompt_text text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.system_prompts enable row level security;

-- Policies for system_prompts
create policy "Admins can manage all system_prompts." on public.system_prompts
  for all using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Doctors can view doctor prompts." on public.system_prompts
  for select using (role = 'doctor');

create policy "Authenticated users can read prompts" on public.system_prompts
  for select using (auth.role() = 'authenticated');

-- 3. Create inquiries table
create table if not exists public.inquiries (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  symptoms text,
  diagnosis_report jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.inquiries enable row level security;

-- Policies for inquiries
create policy "Users can view their own inquiries." on public.inquiries
  for select using (auth.uid() = user_id);

create policy "Users can insert their own inquiries." on public.inquiries
  for insert with check (auth.uid() = user_id);

create policy "Doctors can view all inquiries." on public.inquiries
  for select using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'doctor'
    )
  );

-- 4. Insert default system prompt
insert into public.system_prompts (role, prompt_text)
values ('doctor', 'You are an experienced 老中医 (traditional Chinese medicine practitioner) with decades of clinical experience. Your goal is to conduct a thorough inquiry (问诊 Wèn Zhěn) to gather complete information for an accurate TCM diagnosis.')
on conflict (role) do nothing;

-- 5. Create a trigger to automatically create a profile entry when a new user signs up via Supabase Auth
-- Note: This is optional but helpful. For now, we handle profile creation in the client code (signup).
