//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  post_en: Post_En;
  post_enConnection: Post_EnConnection;
  post_ms: Post_Ms;
  post_msConnection: Post_MsConnection;
  post_zh: Post_Zh;
  post_zhConnection: Post_ZhConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPost_EnArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPost_EnConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Post_EnFilter>;
};


export type QueryPost_MsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPost_MsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Post_MsFilter>;
};


export type QueryPost_ZhArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPost_ZhConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Post_ZhFilter>;
};

export type DocumentFilter = {
  post_en?: InputMaybe<Post_EnFilter>;
  post_ms?: InputMaybe<Post_MsFilter>;
  post_zh?: InputMaybe<Post_ZhFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Post_En | Post_Ms | Post_Zh | Folder;

export type Post_EnAuthor = {
  __typename?: 'Post_enAuthor';
  name?: Maybe<Scalars['String']['output']>;
  picture?: Maybe<Scalars['String']['output']>;
};

export type Post_EnOgImage = {
  __typename?: 'Post_enOgImage';
  url?: Maybe<Scalars['String']['output']>;
};

export type Post_En = Node & Document & {
  __typename?: 'Post_en';
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Post_EnAuthor>;
  ogImage?: Maybe<Post_EnOgImage>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type Post_EnAuthorFilter = {
  name?: InputMaybe<StringFilter>;
  picture?: InputMaybe<ImageFilter>;
};

export type Post_EnOgImageFilter = {
  url?: InputMaybe<ImageFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Post_EnFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<Post_EnAuthorFilter>;
  ogImage?: InputMaybe<Post_EnOgImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Post_EnConnectionEdges = {
  __typename?: 'Post_enConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post_En>;
};

export type Post_EnConnection = Connection & {
  __typename?: 'Post_enConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Post_EnConnectionEdges>>>;
};

export type Post_MsAuthor = {
  __typename?: 'Post_msAuthor';
  name?: Maybe<Scalars['String']['output']>;
  picture?: Maybe<Scalars['String']['output']>;
};

export type Post_Ms = Node & Document & {
  __typename?: 'Post_ms';
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Post_MsAuthor>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Post_MsAuthorFilter = {
  name?: InputMaybe<StringFilter>;
  picture?: InputMaybe<ImageFilter>;
};

export type Post_MsFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<Post_MsAuthorFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Post_MsConnectionEdges = {
  __typename?: 'Post_msConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post_Ms>;
};

export type Post_MsConnection = Connection & {
  __typename?: 'Post_msConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Post_MsConnectionEdges>>>;
};

export type Post_ZhAuthor = {
  __typename?: 'Post_zhAuthor';
  name?: Maybe<Scalars['String']['output']>;
  picture?: Maybe<Scalars['String']['output']>;
};

export type Post_Zh = Node & Document & {
  __typename?: 'Post_zh';
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Post_ZhAuthor>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Post_ZhAuthorFilter = {
  name?: InputMaybe<StringFilter>;
  picture?: InputMaybe<ImageFilter>;
};

export type Post_ZhFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<Post_ZhAuthorFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Post_ZhConnectionEdges = {
  __typename?: 'Post_zhConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post_Zh>;
};

export type Post_ZhConnection = Connection & {
  __typename?: 'Post_zhConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Post_ZhConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePost_en: Post_En;
  createPost_en: Post_En;
  updatePost_ms: Post_Ms;
  createPost_ms: Post_Ms;
  updatePost_zh: Post_Zh;
  createPost_zh: Post_Zh;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePost_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Post_EnMutation;
};


export type MutationCreatePost_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Post_EnMutation;
};


export type MutationUpdatePost_MsArgs = {
  relativePath: Scalars['String']['input'];
  params: Post_MsMutation;
};


export type MutationCreatePost_MsArgs = {
  relativePath: Scalars['String']['input'];
  params: Post_MsMutation;
};


export type MutationUpdatePost_ZhArgs = {
  relativePath: Scalars['String']['input'];
  params: Post_ZhMutation;
};


export type MutationCreatePost_ZhArgs = {
  relativePath: Scalars['String']['input'];
  params: Post_ZhMutation;
};

export type DocumentUpdateMutation = {
  post_en?: InputMaybe<Post_EnMutation>;
  post_ms?: InputMaybe<Post_MsMutation>;
  post_zh?: InputMaybe<Post_ZhMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  post_en?: InputMaybe<Post_EnMutation>;
  post_ms?: InputMaybe<Post_MsMutation>;
  post_zh?: InputMaybe<Post_ZhMutation>;
};

export type Post_EnAuthorMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  picture?: InputMaybe<Scalars['String']['input']>;
};

export type Post_EnOgImageMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
};

export type Post_EnMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Post_EnAuthorMutation>;
  ogImage?: InputMaybe<Post_EnOgImageMutation>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Post_MsAuthorMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  picture?: InputMaybe<Scalars['String']['input']>;
};

export type Post_MsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Post_MsAuthorMutation>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Post_ZhAuthorMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  picture?: InputMaybe<Scalars['String']['input']>;
};

export type Post_ZhMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Post_ZhAuthorMutation>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Post_EnPartsFragment = { __typename: 'Post_en', title: string, excerpt?: string | null, coverImage?: string | null, date?: string | null, body?: any | null, author?: { __typename: 'Post_enAuthor', name?: string | null, picture?: string | null } | null, ogImage?: { __typename: 'Post_enOgImage', url?: string | null } | null };

export type Post_MsPartsFragment = { __typename: 'Post_ms', title: string, excerpt?: string | null, coverImage?: string | null, date?: string | null, body?: any | null, author?: { __typename: 'Post_msAuthor', name?: string | null, picture?: string | null } | null };

export type Post_ZhPartsFragment = { __typename: 'Post_zh', title: string, excerpt?: string | null, coverImage?: string | null, date?: string | null, body?: any | null, author?: { __typename: 'Post_zhAuthor', name?: string | null, picture?: string | null } | null };

export type Post_EnQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Post_EnQuery = { __typename?: 'Query', post_en: { __typename: 'Post_en', id: string, title: string, excerpt?: string | null, coverImage?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, author?: { __typename: 'Post_enAuthor', name?: string | null, picture?: string | null } | null, ogImage?: { __typename: 'Post_enOgImage', url?: string | null } | null } };

export type Post_EnConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Post_EnFilter>;
}>;


export type Post_EnConnectionQuery = { __typename?: 'Query', post_enConnection: { __typename?: 'Post_enConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Post_enConnectionEdges', cursor: string, node?: { __typename: 'Post_en', id: string, title: string, excerpt?: string | null, coverImage?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, author?: { __typename: 'Post_enAuthor', name?: string | null, picture?: string | null } | null, ogImage?: { __typename: 'Post_enOgImage', url?: string | null } | null } | null } | null> | null } };

export type Post_MsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Post_MsQuery = { __typename?: 'Query', post_ms: { __typename: 'Post_ms', id: string, title: string, excerpt?: string | null, coverImage?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, author?: { __typename: 'Post_msAuthor', name?: string | null, picture?: string | null } | null } };

export type Post_MsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Post_MsFilter>;
}>;


export type Post_MsConnectionQuery = { __typename?: 'Query', post_msConnection: { __typename?: 'Post_msConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Post_msConnectionEdges', cursor: string, node?: { __typename: 'Post_ms', id: string, title: string, excerpt?: string | null, coverImage?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, author?: { __typename: 'Post_msAuthor', name?: string | null, picture?: string | null } | null } | null } | null> | null } };

export type Post_ZhQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Post_ZhQuery = { __typename?: 'Query', post_zh: { __typename: 'Post_zh', id: string, title: string, excerpt?: string | null, coverImage?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, author?: { __typename: 'Post_zhAuthor', name?: string | null, picture?: string | null } | null } };

export type Post_ZhConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Post_ZhFilter>;
}>;


export type Post_ZhConnectionQuery = { __typename?: 'Query', post_zhConnection: { __typename?: 'Post_zhConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Post_zhConnectionEdges', cursor: string, node?: { __typename: 'Post_zh', id: string, title: string, excerpt?: string | null, coverImage?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, author?: { __typename: 'Post_zhAuthor', name?: string | null, picture?: string | null } | null } | null } | null> | null } };

export const Post_EnPartsFragmentDoc = gql`
    fragment Post_enParts on Post_en {
  __typename
  title
  excerpt
  coverImage
  date
  author {
    __typename
    name
    picture
  }
  ogImage {
    __typename
    url
  }
  body
}
    `;
export const Post_MsPartsFragmentDoc = gql`
    fragment Post_msParts on Post_ms {
  __typename
  title
  excerpt
  coverImage
  date
  author {
    __typename
    name
    picture
  }
  body
}
    `;
export const Post_ZhPartsFragmentDoc = gql`
    fragment Post_zhParts on Post_zh {
  __typename
  title
  excerpt
  coverImage
  date
  author {
    __typename
    name
    picture
  }
  body
}
    `;
export const Post_EnDocument = gql`
    query post_en($relativePath: String!) {
  post_en(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Post_enParts
  }
}
    ${Post_EnPartsFragmentDoc}`;
export const Post_EnConnectionDocument = gql`
    query post_enConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Post_enFilter) {
  post_enConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Post_enParts
      }
    }
  }
}
    ${Post_EnPartsFragmentDoc}`;
export const Post_MsDocument = gql`
    query post_ms($relativePath: String!) {
  post_ms(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Post_msParts
  }
}
    ${Post_MsPartsFragmentDoc}`;
export const Post_MsConnectionDocument = gql`
    query post_msConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Post_msFilter) {
  post_msConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Post_msParts
      }
    }
  }
}
    ${Post_MsPartsFragmentDoc}`;
export const Post_ZhDocument = gql`
    query post_zh($relativePath: String!) {
  post_zh(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Post_zhParts
  }
}
    ${Post_ZhPartsFragmentDoc}`;
export const Post_ZhConnectionDocument = gql`
    query post_zhConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Post_zhFilter) {
  post_zhConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Post_zhParts
      }
    }
  }
}
    ${Post_ZhPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      post_en(variables: Post_EnQueryVariables, options?: C): Promise<{data: Post_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_EnQueryVariables, query: string}> {
        return requester<{data: Post_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_EnQueryVariables, query: string}, Post_EnQueryVariables>(Post_EnDocument, variables, options);
      },
    post_enConnection(variables?: Post_EnConnectionQueryVariables, options?: C): Promise<{data: Post_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_EnConnectionQueryVariables, query: string}> {
        return requester<{data: Post_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_EnConnectionQueryVariables, query: string}, Post_EnConnectionQueryVariables>(Post_EnConnectionDocument, variables, options);
      },
    post_ms(variables: Post_MsQueryVariables, options?: C): Promise<{data: Post_MsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_MsQueryVariables, query: string}> {
        return requester<{data: Post_MsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_MsQueryVariables, query: string}, Post_MsQueryVariables>(Post_MsDocument, variables, options);
      },
    post_msConnection(variables?: Post_MsConnectionQueryVariables, options?: C): Promise<{data: Post_MsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_MsConnectionQueryVariables, query: string}> {
        return requester<{data: Post_MsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_MsConnectionQueryVariables, query: string}, Post_MsConnectionQueryVariables>(Post_MsConnectionDocument, variables, options);
      },
    post_zh(variables: Post_ZhQueryVariables, options?: C): Promise<{data: Post_ZhQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_ZhQueryVariables, query: string}> {
        return requester<{data: Post_ZhQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_ZhQueryVariables, query: string}, Post_ZhQueryVariables>(Post_ZhDocument, variables, options);
      },
    post_zhConnection(variables?: Post_ZhConnectionQueryVariables, options?: C): Promise<{data: Post_ZhConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_ZhConnectionQueryVariables, query: string}> {
        return requester<{data: Post_ZhConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Post_ZhConnectionQueryVariables, query: string}, Post_ZhConnectionQueryVariables>(Post_ZhConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  