import { useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { createPortal } from "react-dom";
import { useRouter } from "next/navigation";
import { useDoctorLevel, useLanguage, useAuth } from "@/stores/useAppStore";
import { Stethoscope, ArrowLeft } from "lucide-react";
import { extractDiagnosisTitle, extractConstitutionType } from "@/lib/tcm-utils";
import { useDiagnosisReportState } from "./report/hooks/useDiagnosisReportState";
import { useDiagnosisReportActions } from "./report/hooks/useDiagnosisReportActions";
import {
  getFoodRecommendations,
  getFoodsToAvoid,
  getRecipes,
} from "./report/utils/reportDataTransformers";

// Sub-components
import { ReportHeader } from "./report/ReportHeader";
import { ReportPatientInfo } from "./report/ReportPatientInfo";
import { ReportDiagnosisSection } from "./report/ReportDiagnosisSection";
import { ReportRecommendations } from "./report/ReportRecommendations";
import { ReportActions } from "./report/ReportActions";
import { PractitionerList } from "./report/PractitionerList";
import { ViewSwitcher, type ViewMode } from "./report/ViewSwitcher";
import { ReportChatWindow, ReportChatButton, type Message } from "./ReportChatWindow";
import { InfographicsGenerator } from "./InfographicsGenerator";
import { SaveToDashboardBanner } from "@/components/patient/SaveToDashboardBanner";
import { DoctorVerificationModal } from "@/components/doctor-verification";

import type { DiagnosisReport } from "@/types/database";
import type { PDFPatientInfo, PDFReportOptions, PDFGenerationData } from "@/types/pdf";

// Interfaces
interface DiagnosisReportProps {
  data: DiagnosisReport | PDFGenerationData;
  patientInfo?: PDFPatientInfo;
  reportOptions?: PDFReportOptions;
  smartConnectData?: Record<string, unknown>;
  onRestart: () => void;
  saved?: boolean;
  isDoctorView?: boolean;
  /** When true, sends a one-time Telegram notification when the report is first shown (e.g. at end of wizard). */
  notifyOnFirstView?: boolean;
}

// Translations (Same as original)
const translations = {
  en: {
    title: "TCM Diagnosis Report",
    subtitle: "Traditional Chinese Medicine Analysis",
    generated: "Generated",
    mainDiagnosis: "MAIN DIAGNOSIS",
    constitution: "Constitution",
    detailedAnalysis: "DETAILED ANALYSIS",
    dietaryRecommendations: "DIETARY RECOMMENDATIONS",
    recommendedFoods: "Recommended Foods:",
    foodsToAvoid: "Foods to Avoid:",
    lifestyleRecommendations: "LIFESTYLE RECOMMENDATIONS",
    exercise: "EXERCISE SUGGESTIONS",
    acupoints: "ACUPOINTS",
    footer1: "This report is generated by Sihat TCM AI Assistant for informational purposes only.",
    footer2: "Please consult a licensed TCM practitioner for professional medical advice.",
    fileName: "TCM_Diagnosis",
    viewFullReport: "View Full Report",
    reportSummary: "TCM Report Summary",
    chatReference: "Reference while chatting",
    diagnosis: "Diagnosis",
  },
  zh: {
    title: "中医诊断报告",
    subtitle: "传统中医药分析",
    generated: "生成日期",
    mainDiagnosis: "主要诊断",
    constitution: "体质",
    detailedAnalysis: "详细分析",
    dietaryRecommendations: "饮食建议",
    recommendedFoods: "推荐食物：",
    foodsToAvoid: "避免食物：",
    lifestyleRecommendations: "生活方式建议",
    exercise: "运动建议",
    acupoints: "穴位按摩",
    footer1: "本报告由 Sihat 中医AI助手生成，仅供参考。",
    footer2: "如需专业医疗建议，请咨询持证中医师。",
    fileName: "中医诊断报告",
    viewFullReport: "查看完整报告",
    reportSummary: "中医报告摘要",
    chatReference: "对话时参考",
    diagnosis: "诊断",
  },
  ms: {
    title: "Laporan Diagnosis TCM",
    subtitle: "Analisis Perubatan Tradisional Cina",
    generated: "Dijana pada",
    mainDiagnosis: "DIAGNOSIS UTAMA",
    constitution: "Perlembagaan",
    detailedAnalysis: "ANALISIS TERPERINCI",
    dietaryRecommendations: "CADANGAN PEMAKANAN",
    recommendedFoods: "Makanan Disyorkan:",
    foodsToAvoid: "Makanan Perlu Dielakkan:",
    lifestyleRecommendations: "CADANGAN GAYA HIDUP",
    exercise: "CADANGAN SENAMAN",
    acupoints: "TITIK AKUPUNKTUR",
    footer1: "Laporan ini dijana oleh Pembantu AI Sihat TCM untuk tujuan maklumat sahaja.",
    footer2: "Sila rujuk pengamal TCM berlesen untuk nasihat perubatan profesional.",
    fileName: "Laporan_Diagnosis_TCM",
    viewFullReport: "Lihat Laporan Penuh",
    reportSummary: "Ringkasan Laporan TCM",
    chatReference: "Rujukan semasa bersembang",
    diagnosis: "Diagnosis",
  },
};

export function DiagnosisReport({
  data,
  patientInfo,
  reportOptions,
  smartConnectData,
  onRestart,
  saved,
  isDoctorView = false,
  notifyOnFirstView = false,
}: DiagnosisReportProps) {
  const router = useRouter();
  const { user } = useAuth();
  const reportViewedNotificationSent = useRef(false);

  // Notify (e.g. Telegram) when user first sees the Comprehensive TCM Report — once per mount
  useEffect(() => {
    if (!notifyOnFirstView || reportViewedNotificationSent.current) return;
    reportViewedNotificationSent.current = true;
    fetch("/api/notifications/report-viewed", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ isGuest: !user }),
    }).catch(() => {});
  }, [notifyOnFirstView, user]);
  const { getDoctorInfo } = useDoctorLevel();
  const doctorInfo = getDoctorInfo();
  // @ts-ignore
  const { language } = useLanguage();
  const t = translations[language as keyof typeof translations];
  const opts = reportOptions || {};

  // Use extracted hooks
  const {
    viewMode,
    isChatOpen,
    isInfographicsOpen,
    isVerificationModalOpen,
    activeQuestion,
    isChatExpanded,
    mounted,
    chatMessages,
    setChatMessages,
    isSaving,
    hasSaved,
    doctors,
    loadingDoctors,
    setViewMode,
    setIsChatOpen,
    setIsInfographicsOpen,
    setIsVerificationModalOpen,
    setActiveQuestion,
    setIsChatExpanded,
    setIsSaving,
    setHasSaved,
  } = useDiagnosisReportState({ saved });

  const { downloadPDF, shareReport, handleSaveToHistory, handleRequestVerification } =
    useDiagnosisReportActions({
      data,
      patientInfo,
      reportOptions,
      smartConnectData,
      language,
      translations,
      setIsSaving,
      setHasSaved,
      setIsVerificationModalOpen,
    });

  // Animation Variants
  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1, delayChildren: 0.1 },
    },
  };

  const item = {
    hidden: { opacity: 0, y: 15, scale: 0.98 },
    show: {
      opacity: 1,
      y: 0,
      scale: 1,
      transition: { type: "spring" as const, stiffness: 220, damping: 20 },
    },
  };

  // Process Data
  const diagnosisText = extractDiagnosisTitle(data.diagnosis);
  const constitutionText = extractConstitutionType(data.constitution);
  const analysisText =
    typeof data.analysis === "string" ? data.analysis : data.analysis?.summary || "";

  // Use extracted data transformers
  const foodRecommendations = getFoodRecommendations(data);
  const foodsToAvoid = getFoodsToAvoid(data);
  const recipes = getRecipes(data);

  const handleSectionClick = (question: string) => {
    setActiveQuestion(question);
    setIsChatOpen(true);
  };

  // Actions are now provided by useDiagnosisReportActions hook

  // Mobile Summary
  const MobileReportSummary = () => (
    <div className="bg-white/80 backdrop-blur-md p-4 border-b border-stone-200 z-50">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gradient-to-br from-emerald-100 to-teal-100 rounded-full flex items-center justify-center shadow-inner">
            <Stethoscope className="w-5 h-5 text-emerald-600" />
          </div>
          <div>
            <h3 className="font-semibold text-slate-800 text-sm">{t.reportSummary}</h3>
            <p className="text-xs text-slate-500">{t.chatReference}</p>
          </div>
        </div>
        <button
          onClick={() => setIsChatExpanded(false)}
          className="text-xs font-medium px-4 py-2 bg-slate-900 text-white rounded-full shadow-lg hover:shadow-xl hover:bg-slate-800 transition-all"
        >
          {t.viewFullReport}
        </button>
      </div>
      <div className="mt-3 bg-stone-50 rounded-xl p-3 border border-stone-100">
        <p className="text-xs text-stone-500 font-medium uppercase tracking-wider mb-1">
          {t.diagnosis}
        </p>
        <p className="text-sm font-semibold text-slate-800 line-clamp-2">{diagnosisText}</p>
      </div>
    </div>
  );

  const getBackgroundClass = () => {
    switch (viewMode) {
      case "classic":
        return "bg-[#F9F7F5]"; // Paper-like
      case "summary":
        return "bg-slate-50";
      default:
        return "bg-[#F2F2F7]"; // iOS System Gray 6
    }
  };

  const getContainerClass = () => {
    if (viewMode === "classic")
      return "max-w-4xl mx-auto bg-white shadow-sm border border-stone-200 min-h-screen my-4 md:my-8 p-6 md:p-12 print:p-0 print:m-0 print:border-none";
    if (viewMode === "summary") return "max-w-xl mx-auto py-8";
    return "max-w-4xl mx-auto pb-24 md:pb-12"; // Modern usually has generous padding
  };

  const content = (
    <div
      className={`min-h-screen transition-colors duration-500 ${getBackgroundClass()} ${isChatExpanded ? "fixed inset-0 z-50 flex flex-col md:flex-row overflow-hidden" : ""}`}
    >
      {/* Expanded Chat View (Mobile Overlay or Side-by-Side) */}
      {isChatExpanded && (
        <div className="md:hidden">
          <MobileReportSummary />
        </div>
      )}

      <div
        className={`w-full px-4 md:px-6 ${getContainerClass()} ${
          isChatExpanded
            ? "hidden md:block md:w-1/2 h-full overflow-y-auto p-6 scrollbar-hide border-r border-stone-200 !m-0 !max-w-none"
            : ""
        }`}
      >
        {!isChatExpanded && (
          <div className="py-6 flex justify-center sticky top-0 z-40 pointer-events-none">
            {/* Only show switcher if not expanded chat */}
            <div className="bg-white/50 backdrop-blur-xl rounded-full p-1 shadow-sm border border-white/20 pointer-events-auto">
              <ViewSwitcher currentMode={viewMode} onChange={setViewMode} />
            </div>
          </div>
        )}

        {/* Save to Dashboard Banner */}
        <div className="mb-6">
          <SaveToDashboardBanner
            isGuest={!user}
            isSaved={hasSaved}
            onViewDashboard={() => router.push("/patient")}
          />
        </div>

        {/* REPORT CONTENT */}
        <motion.div
          key={viewMode}
          variants={container}
          initial="hidden"
          animate="show"
          className={`space-y-6 ${viewMode === "classic" ? "font-serif space-y-8" : ""}`}
        >
          <ReportHeader
            doctorInfo={doctorInfo}
            hasSaved={hasSaved}
            // @ts-ignore
            language={language}
            timestamp={data.timestamp}
            includeTimestamp={opts.includeTimestamp ?? true}
            variants={item}
            viewMode={viewMode}
          />

          {viewMode !== "summary" && (
            <ReportPatientInfo
              patientInfo={patientInfo}
              smartConnectData={smartConnectData}
              reportOptions={opts}
              variants={item}
              viewMode={viewMode}
            />
          )}

          <ReportDiagnosisSection
            data={data}
            diagnosisText={diagnosisText}
            constitutionText={constitutionText}
            analysisText={analysisText}
            variants={item}
            viewMode={viewMode}
          />

          {viewMode !== "summary" && (
            <ReportRecommendations
              data={data}
              reportOptions={opts}
              foodRecommendations={foodRecommendations}
              foodsToAvoid={foodsToAvoid}
              recipes={recipes}
              handleSectionClick={handleSectionClick}
              variants={item}
              viewMode={viewMode}
            />
          )}

          <motion.div variants={item}>
            <div
              className={`rounded-xl p-5 md:p-6 text-center ${viewMode === "classic" ? "bg-transparent italic text-stone-600 border-t border-stone-200 rounded-none" : "bg-white/60 backdrop-blur-sm border border-white/40"}`}
            >
              <p className="text-stone-500 text-sm md:text-base leading-relaxed">
                {data.disclaimer ||
                  "This report is generated by Sihat TCM AI Assistant for informational purposes only. It is not a substitute for professional medical advice. Please consult a licensed TCM practitioner for diagnosis and treatment."}
              </p>
            </div>
          </motion.div>

          {!isDoctorView && viewMode !== "summary" && (
            <motion.div variants={item}>
              <PractitionerList doctors={doctors} loading={loadingDoctors} variants={item} />
            </motion.div>
          )}

          <ReportActions
            onChatOpen={() => setIsChatOpen(true)}
            // @ts-ignore
            onDownloadPDF={() => downloadPDF(language)}
            onShare={shareReport}
            onSave={handleSaveToHistory}
            onRestart={onRestart}
            onInfographicsOpen={() => setIsInfographicsOpen(true)}
            onRequestVerification={handleRequestVerification}
            isSaving={isSaving}
            hasSaved={hasSaved}
            // @ts-ignore
            language={language}
            variants={item}
            isDoctorView={isDoctorView}
            viewMode={viewMode}
          />
        </motion.div>
      </div>

      {/* CHAT WINDOW HANDLING */}
      {isChatExpanded && (
        <div className="w-full md:w-1/2 flex-1 md:h-full bg-slate-50/50 backdrop-blur-3xl relative">
          <ReportChatWindow
            reportData={data}
            patientInfo={patientInfo}
            isOpen={true}
            onClose={() => setIsChatExpanded(false)}
            initialMessage={activeQuestion || undefined}
            onMessageSent={() => setActiveQuestion(null)}
            isExpanded={true}
            onToggleExpand={() => setIsChatExpanded(false)}
            messages={chatMessages}
            onMessagesChange={setChatMessages}
          />
        </div>
      )}

      {/* Floating Chat Bubble & Modal */}
      {!isChatExpanded && (
        <>
          <ReportChatButton onClick={() => setIsChatOpen(true)} />
          <ReportChatWindow
            reportData={data}
            patientInfo={patientInfo}
            isOpen={isChatOpen}
            onClose={() => setIsChatOpen(false)}
            initialMessage={activeQuestion || undefined}
            onMessageSent={() => setActiveQuestion(null)}
            isExpanded={false}
            onToggleExpand={() => {
              setIsChatOpen(false);
              setIsChatExpanded(true);
            }}
            messages={chatMessages}
            onMessagesChange={setChatMessages}
          />
        </>
      )}

      <InfographicsGenerator
        isOpen={isInfographicsOpen}
        onClose={() => setIsInfographicsOpen(false)}
        reportData={data}
        patientInfo={patientInfo}
      />

      {/* Doctor Verification Modal */}
      <DoctorVerificationModal
        isOpen={isVerificationModalOpen}
        onClose={() => setIsVerificationModalOpen(false)}
        reportData={data as any}
        patientData={{
          name: patientInfo?.name,
          age: patientInfo?.age ? Number(patientInfo.age) : undefined,
          gender: patientInfo?.gender,
        }}
      />
    </div>
  );

  if (isChatExpanded && mounted) {
    return createPortal(content, document.body);
  }

  return content;
}
