import {
  Moon,
  Music,
  Waves,
  Droplets,
  TreePine,
  Flame,
  Mountain,
  Coins,
  CloudRain,
} from "lucide-react";
import { SleepMusicTrack } from "./types";

export const SLEEP_MUSIC_TRACKS: SleepMusicTrack[] = [
  {
    id: "water",
    name: "Flowing Water",
    nameZh: "流水声",
    nameMs: "Air Mengalir",
    description: "Calming water sounds to nourish Kidney Yin",
    descriptionZh: "滋养肾阴的流水声",
    descriptionMs: "Bunyi air yang menenangkan untuk menyuburkan Yin Buah Pinggang",
    icon: <Waves className="w-5 h-5" />,
    audioPath: "https://actions.google.com/sounds/v1/water/stream_water.ogg",
    color: "text-blue-600",
    gradient: "from-blue-500/20 to-cyan-500/20",
  },
  {
    id: "rain",
    name: "Gentle Rain",
    nameZh: "细雨声",
    nameMs: "Hujan Renyai",
    description: "Rain sounds to calm the Shen (spirit)",
    descriptionZh: "安神养心的雨声",
    descriptionMs: "Bunyi hujan untuk menenangkan Shen (roh)",
    icon: <CloudRain className="w-5 h-5" />,
    audioPath: "https://actions.google.com/sounds/v1/weather/rain_heavy_loud.ogg",
    color: "text-sky-600",
    gradient: "from-sky-500/20 to-slate-500/20",
  },
  {
    id: "earth",
    name: "Earth Drums",
    nameZh: "大地鼓声",
    nameMs: "Gendang Bumi",
    description: "Steady rhythms to ground the Spleen",
    descriptionZh: "稳定脾胃的鼓点节奏",
    descriptionMs: "Irama mantap untuk mengukuhkan Limpa",
    icon: <Mountain className="w-5 h-5" />,
    audioPath: "https://actions.google.com/sounds/v1/nature/nature_sounds_night.ogg",
    color: "text-amber-600",
    gradient: "from-amber-500/20 to-orange-500/20",
  },
  {
    id: "fire",
    name: "Warm Tones",
    nameZh: "温暖音调",
    nameMs: "Nada Hangat",
    description: "Gentle warmth to support Yang energy",
    descriptionZh: "温养阳气的舒缓音调",
    descriptionMs: "Kehangatan lembut untuk menyokong tenaga Yang",
    icon: <Flame className="w-5 h-5" />,
    audioPath: "https://actions.google.com/sounds/v1/ambiences/fire.ogg",
    color: "text-red-500",
    gradient: "from-red-500/20 to-orange-500/20",
  },
  {
    id: "metal",
    name: "Crystal Bowls",
    nameZh: "水晶钵音",
    nameMs: "Mangkuk Kristal",
    description: "Clear metallic tones to ease the Lung Qi",
    descriptionZh: "疏通肺气的清澈金属音",
    descriptionMs: "Nada logam yang jernih untuk melegakan Qi Paru-paru",
    icon: <Coins className="w-5 h-5" />,
    audioPath: "https://actions.google.com/sounds/v1/alarms/temple_bell.ogg",
    color: "text-slate-500",
    gradient: "from-slate-400/20 to-gray-500/20",
  },
  {
    id: "wood",
    name: "Forest Breeze",
    nameZh: "林间微风",
    nameMs: "Angin Hutan",
    description: "Gentle winds through trees to soothe the Liver",
    descriptionZh: "疏肝解郁的林间风声",
    descriptionMs: "Angin lembut melalui pokok untuk menenangkan Hati",
    icon: <TreePine className="w-5 h-5" />,
    audioPath: "https://actions.google.com/sounds/v1/nature/forest_wind.ogg",
    color: "text-green-600",
    gradient: "from-green-500/20 to-emerald-500/20",
  },
  {
    id: "guqin",
    name: "Guqin Melody",
    nameZh: "古琴曲",
    nameMs: "Melodi Guqin",
    description: "Traditional Chinese zither for deep relaxation",
    descriptionZh: "古琴悠扬，深度放松",
    descriptionMs: "Kecapi tradisional Cina untuk relaksasi mendalam",
    icon: <Music className="w-5 h-5" />,
    audioPath: "https://actions.google.com/sounds/v1/relax/meditation.ogg",
    color: "text-purple-600",
    gradient: "from-purple-500/20 to-indigo-500/20",
  },
  {
    id: "meditation",
    name: "Meditation Music",
    nameZh: "冥想音乐",
    nameMs: "Muzik Meditasi",
    description: "Relaxing music for sleep preparation",
    descriptionZh: "助眠的放松音乐",
    descriptionMs: "Muzik santai untuk persediaan tidur",
    icon: <Moon className="w-5 h-5" />,
    audioPath: "https://actions.google.com/sounds/v1/relax/meditation.ogg",
    color: "text-indigo-600",
    gradient: "from-indigo-500/20 to-violet-500/20",
  },
];

export const DEFAULT_VOLUMES = {
  primary: 0.6,
  secondary: 0.4,
  ambient: 0.3,
  guqin: 0.5,
  meditation: 0.7,
};
